//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты_в_группах
    {
        public System.Guid ID_студента { get; set; }
        public System.Guid ID_группы { get; set; }
        public int Код_формы_оплаты { get; set; }
    
        public virtual Группы Группы { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
